package tools

import (
	"context"

	"bundletool-mcp/internal/bundletool"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type ExtractApksArgs struct {
	ApksPath        string `json:"apks_path" jsonschema:"Absolute path to the .apks archive file."`
	DeviceSpec      string `json:"device_spec" jsonschema:"Path to the device spec JSON file (generated by get_device_spec)."`
	OutputDir       string `json:"output_dir,omitempty" jsonschema:"Directory where the matched APKs will be extracted. If omitted, uses a temp dir."`
	Modules         string `json:"modules,omitempty" jsonschema:"Comma-separated list of modules to extract."`
	Instant         bool   `json:"instant,omitempty" jsonschema:"Extract instant modules instead of installable."`
	IncludeMetadata bool   `json:"include_metadata,omitempty" jsonschema:"Produce metadata.json in the output directory."`
}

func (h *Handlers) handleExtractApks(ctx context.Context, req *mcp.CallToolRequest, args ExtractApksArgs) (*mcp.CallToolResult, any, error) {
	opts := bundletool.ExtractApksOptions{
		ApksPath:        args.ApksPath,
		DeviceSpec:      args.DeviceSpec,
		OutputDir:       args.OutputDir,
		Modules:         args.Modules,
		Instant:         args.Instant,
		IncludeMetadata: args.IncludeMetadata,
	}
	out, err := h.client.ExtractApks(ctx, opts)
	return formatResult(out, err)
}
